nameOverride: warda-youssef
fullnameOverride: paas-warda-youssef
deploymentStrategy: Rolling
image:
  repository: 192.168.56.129:30002/paas/warda-youssef
  tag: '78'
  digest: ''
  pullPolicy: IfNotPresent
imagePullSecrets:
- name: harbor-regcred
service:
  targetPort: 80
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 25m
    memory: 64Mi
probes:
  type: tcp
  readiness:
    initialDelaySeconds: 3
    periodSeconds: 5
    failureThreshold: 6
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 15
    failureThreshold: 6
ingress:
  enabled: true
  className: traefik
  hosts:
  - host: warda-youssef.192.168.56.129.nip.io
  tls: []
