image:
  repository: 192.168.56.129:30002/paas/sanhome
  tag: "17"
  digest: ""
imagePullSecrets:
  - name: harbor-regcred
service:
  targetPort: 8080
podSecurityContext:
  runAsUser: 65532
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
env: []
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: sanhome.192.168.56.129.nip.io
  tls: []
