apiVersion: v1
kind: Service
metadata:
  name: {{ include "dockerized-nextjs.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dockerized-nextjs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "dockerized-nextjs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
