image:
  repository: 192.168.56.129:30002/paas/demo-angular-app
  tag: "380"
  digest: ""
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: harbor-regcred
service:
  targetPort: 80
resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 256Mi
env: []
deploymentStrategy: Rolling
ingress:
  enabled: true
  className: traefik
  hosts:
    - host: demo-angular-app.192.168.56.129.nip.io
  tls: []
