image:
  repository: 192.168.56.129:30002/paas/demo-angular-app
  tag: '389'
  digest: ''
  pullPolicy: IfNotPresent
imagePullSecrets:
- name: harbor-regcred
service:
  targetPort: 80
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 25m
    memory: 64Mi
env: []
deploymentStrategy: Rolling
ingress:
  enabled: true
  className: traefik
  hosts:
  - host: demo-angular-app.192.168.56.129.nip.io
  tls: []
