{{- if include "demo-angular-app.staticNginx" . | eq "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: paas-nginx-override
  labels:
    app.kubernetes.io/name: {{ include "demo-angular-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
{{- end }}
