image:
  repository: 192.168.56.129:30002/paas/tutorial-react-docker
  tag: "608"
  digest: ""
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: harbor-regcred
service:
  targetPort: 80
ingress:
  enabled: true
  className: traefik
  hosts:
    - host: tutorial-react-docker.192.168.56.129.nip.io
  tls: []
resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 256Mi
env:
  - name: APP_BASE_URL
    value: http://tutorial-react-docker.192.168.56.129.nip.io:30659
  - name: NEXT_PUBLIC_APP_URL
    value: http://tutorial-react-docker.192.168.56.129.nip.io:30659
  - name: NEXT_PUBLIC_SITE_URL
    value: http://tutorial-react-docker.192.168.56.129.nip.io:30659
  - name: PUBLIC_URL
    value: http://tutorial-react-docker.192.168.56.129.nip.io:30659
deploymentStrategy: Rolling
probes:
  type: tcp
  readiness:
    initialDelaySeconds: 3
    periodSeconds: 5
    failureThreshold: 6
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 15
    failureThreshold: 6
