image:
  repository: 192.168.56.129:30002/paas/text-to-floorplan-2d
  tag: "201"
  pullPolicy: IfNotPresent
  digest: ""
imagePullSecrets:
  - name: harbor-regcred
service:
  targetPort: 3000
resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 256Mi
env: []
ingress:
  enabled: true
  className: traefik
  hosts:
    - host: text-to-floorplan-2d.192.168.56.129.nip.io
  tls: []
