apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "simple-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "simple-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if eq (.Values.deploymentStrategy | default "Rolling") "BlueGreen" }}
    paas.io/slot: {{ .Values.activeSlot | default "blue" }}
    {{- end }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
