image:
  repository: 192.168.56.129:30002/paas/react-example
  tag: '79'
  digest: ''
  pullPolicy: IfNotPresent
nameOverride: react-example
fullnameOverride: paas-react-example
imagePullSecrets:
- name: harbor-regcred
service:
  targetPort: 3000
probes:
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 6
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 20
    failureThreshold: 6
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 25m
    memory: 64Mi
env:
- name: APP_BASE_URL
  value: http://react-example.192.168.56.129.nip.io:30659
- name: NEXT_PUBLIC_APP_URL
  value: http://react-example.192.168.56.129.nip.io:30659
- name: NEXT_PUBLIC_SITE_URL
  value: http://react-example.192.168.56.129.nip.io:30659
- name: PUBLIC_URL
  value: http://react-example.192.168.56.129.nip.io:30659
deploymentStrategy: Rolling
ingress:
  enabled: true
  className: traefik
  hosts:
  - host: react-example.192.168.56.129.nip.io
  tls: []
nodeSelector:
  kubernetes.io/hostname: master
