image:
  repository: harbor.192.168.56.129.nip.io:30002/paas/test-app
  tag: "262"
  digest: ""
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  - name: APP_BASE_URL
    value: http://test-app.192.168.56.129.nip.io:30659
  - name: NEXT_PUBLIC_APP_URL
    value: http://test-app.192.168.56.129.nip.io:30659
  - name: NEXT_PUBLIC_SITE_URL
    value: http://test-app.192.168.56.129.nip.io:30659
  - name: PUBLIC_URL
    value: http://test-app.192.168.56.129.nip.io:30659
ingress:
  enabled: true
  className: traefik
  hosts:
    - host: test-app.192.168.56.129.nip.io
  tls: []
imagePullSecrets:
  - name: harbor-regcred
deploymentStrategy: Rolling
service:
  targetPort: 3000
probes:
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 6
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 20
    failureThreshold: 6
nameOverride: test-app
fullnameOverride: paas-test-app
