nameOverride: roll-dice-app
fullnameOverride: paas-roll-dice-app
deploymentStrategy: Rolling
image:
  repository: 192.168.56.129:30002/paas/roll-dice-app
  tag: '728'
  digest: ''
  pullPolicy: IfNotPresent
imagePullSecrets:
- name: harbor-regcred
service:
  targetPort: 3000
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 25m
    memory: 64Mi
probes:
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 6
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 20
    failureThreshold: 6
ingress:
  enabled: true
  className: traefik
  hosts:
  - host: roll-dice-app.192.168.56.129.nip.io
  tls: []
