nameOverride: roll-dice-app
fullnameOverride: paas-roll-dice-app
deploymentStrategy: Rolling
image:
  repository: 192.168.56.129:30002/paas/roll-dice-app
  tag: "783"
  digest: ""
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: harbor-regcred
service:
  targetPort: 3000
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 25m
    memory: 64Mi
probes:
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 6
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 20
    failureThreshold: 6
ingress:
  enabled: true
  className: traefik
  hosts:
    - host: roll-dice-app.192.168.56.129.nip.io
  tls: []
env:
  - name: APP_BASE_URL
    value: https://roll-dice-app.apps.local
  - name: NEXT_PUBLIC_APP_URL
    value: https://roll-dice-app.apps.local
  - name: NEXT_PUBLIC_SITE_URL
    value: https://roll-dice-app.apps.local
  - name: PUBLIC_URL
    value: https://roll-dice-app.apps.local
