image:
  repository: gcr.io/google-samples/hello-app
  tag: '1.0'
  digest: ''
imagePullSecrets: []
podSecurityContext:
  runAsUser: 65532
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
env: []
ingress:
  enabled: true
  className: traefik
  hosts:
  - host: sample-app.192.168.56.129.nip.io
  tls: []
