image:
  repository: 192.168.56.129:30002/paas/simple-app
  tag: "9"
  digest: ""
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: harbor-regcred
ingress:
  enabled: true
  className: traefik
  hosts:
    - host: simple-app.192.168.56.129.nip.io
  tls: []
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
env: []
