image:
  repository: 192.168.56.129:30002/paas/profit-margin-sponsoring-facebook
  tag: "194"
  pullPolicy: IfNotPresent
  digest: ""
imagePullSecrets:
  - name: harbor-regcred
service:
  targetPort: 3000
ingress:
  enabled: true
  className: traefik
  hosts:
    - host: profit-margin-sponsoring-facebook.192.168.56.129.nip.io
  tls: []
resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 256Mi
env: []
