image:
  repository: 192.168.56.129:30002/paas/warda
  tag: "329"
  digest: ""
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: harbor-regcred
service:
  targetPort: 3000
resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 256Mi
env: []
deploymentStrategy: BlueGreen
activeSlot: green
ingress:
  enabled: true
  className: traefik
  hosts:
    - host: warda.192.168.56.129.nip.io
  tls: []
blue:
  image:
    repository: 192.168.56.129:30002/paas/warda
    tag: "333"
    digest: ""
green:
  image:
    repository: 192.168.56.129:30002/paas/warda
    tag: "329"
    digest: ""
