image:
  repository: 192.168.56.129:30002/paas/python-fastapi-demo-docker
  tag: "264"
  digest: ""
  pullPolicy: IfNotPresent
nameOverride: python-fastapi-demo-docker
fullnameOverride: paas-python-fastapi-demo-docker
imagePullSecrets:
  - name: harbor-regcred
service:
  targetPort: 8000
probes:
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 12
  liveness:
    initialDelaySeconds: 90
    periodSeconds: 20
    failureThreshold: 6
resources:
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 50m
    memory: 128Mi
env:
  - name: APP_BASE_URL
    value: http://python-fastapi-demo-docker.192.168.56.129.nip.io:30659
  - name: NEXT_PUBLIC_APP_URL
    value: http://python-fastapi-demo-docker.192.168.56.129.nip.io:30659
  - name: NEXT_PUBLIC_SITE_URL
    value: http://python-fastapi-demo-docker.192.168.56.129.nip.io:30659
  - name: PUBLIC_URL
    value: http://python-fastapi-demo-docker.192.168.56.129.nip.io:30659
deploymentStrategy: Rolling
ingress:
  enabled: true
  className: traefik
  hosts:
    - host: python-fastapi-demo-docker.192.168.56.129.nip.io
  tls: []
